//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbriel.ArcMapUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.geohash.org/~~GEOHASH~~")]
        public string GeohashIDLaunchURL {
            get {
                return ((string)(this["GeohashIDLaunchURL"]));
            }
            set {
                this["GeohashIDLaunchURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeohashIDLaunchURLEnabled {
            get {
                return ((bool)(this["GeohashIDLaunchURLEnabled"]));
            }
            set {
                this["GeohashIDLaunchURLEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddPhotoPointLastUsedPath {
            get {
                return ((string)(this["AddPhotoPointLastUsedPath"]));
            }
            set {
                this["AddPhotoPointLastUsedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101,67,68,128,57,60,118")]
        public string AddPhotoPointColumnWidths {
            get {
                return ((string)(this["AddPhotoPointColumnWidths"]));
            }
            set {
                this["AddPhotoPointColumnWidths"] = value;
            }
        }
    }
}
