//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbriel.ArcGIS.Spatialite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddSpatialiteLastFolder {
            get {
                return ((string)(this["AddSpatialiteLastFolder"]));
            }
            set {
                this["AddSpatialiteLastFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportSpatialite_HighlightChecked {
            get {
                return ((bool)(this["ExportSpatialite_HighlightChecked"]));
            }
            set {
                this["ExportSpatialite_HighlightChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportSpatialite_OnlyCurrentExtent {
            get {
                return ((bool)(this["ExportSpatialite_OnlyCurrentExtent"]));
            }
            set {
                this["ExportSpatialite_OnlyCurrentExtent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportSpatialite_OnlySelectedFeatures {
            get {
                return ((bool)(this["ExportSpatialite_OnlySelectedFeatures"]));
            }
            set {
                this["ExportSpatialite_OnlySelectedFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};Version=3;")]
        public string BasicSQliteConnectionString {
            get {
                return ((string)(this["BasicSQliteConnectionString"]));
            }
            set {
                this["BasicSQliteConnectionString"] = value;
            }
        }
    }
}
